version: '3.4'
x-common-variables: &tsa_variables
  DB_SERVER: ${DB_SERVER}
  DB_DATABASE: ${DB_DATABASE}
  DB_USER_DATABASE: ${DB_USER_DATABASE}
  DB_USER: ${DB_USER}
  DB_USER_PASS: ${DB_USER_PASS}

services:

  sbt:
    image: docker-registry.naturkundemuseum.berlin/tsa/tsa-gbif-tool:latest
    container_name: tsa-gbif-tool
    ports:
      - "9000:9000"
    volumes:
      - ./entrypoint.sh:/tsa-gbif-tool/entrypoint.sh
    entrypoint: /bin/bash /tsa-gbif-tool/entrypoint.sh
    environment:
      <<: *tsa_variables
